### ISSUE TITLE
Does not support .Net Core?

### ISSUE THREAD

**Issue by jacking75** [neuecc/CloudStructures#17]
So far we have used CloudStructures well.
thank you.

In the future, I want to use .Net Core instead of .NET Framework. Does not support .Net Core?

**Comment by neuecc** [comment]
I'm using CloudStructures heavily in our production.
So I should improve more, it exists my plan.

**Comment by jacking75** [comment]
very thank you

**Comment by gmikettt** [comment]
hello, @neuecc, thank you for CloudStructures.
is there any progress here?

**Comment by xin9le** [comment]
This library finally corresponded to .NET Standard. (#18)
