### ISSUE TITLE
More RedisConfig option

### ISSUE THREAD

**Issue by neuecc** [neuecc/CloudStructures#22]
@xin9le 
Currently, RedisConfig only accepts string connection-string.
Could you add ConfigurationOptions overload?
`public RedisConfig(string name, ConfigurationOptions configurationOptions, int? database = default(int?))`

One more, ConfigurationOptions(connection-string) has defaultDatabase option.
https://stackexchange.github.io/StackExchange.Redis/Configuration#configuration-options

It is duplicate as `RedisConfig.Database`.
Perhaps you should delete this property, However, if compatibility must be maintained
We can change to
`Database = database ?? Options.DefaultDatabase`.

**Comment by xin9le** [comment]
Thanks for your good requesting. I added following ctor overload :)

```
public RedisConfig(string name, ConfigurationOptions options, int? database = default)
{ }
```
