### ISSUE TITLE
How can I retrieve specific element from list using filter?

### ISSUE THREAD

**Issue by ashuthinks** [neuecc/CloudStructures#4]
var list = new RedisList<Customer>(RedisServer.Default, "customer-key");
            await list.Delete();
            await list.LeftPush(new[] { new Customer { Id = 111, Name = "abcus" }, 
                                        new Customer { Id = 222, Name = "beten" }, 
                                        new Customer { Id = 333, Name = "censor" }, 
                                        new Customer { Id = 444, Name = "dany" } });

var persons = await list.Range(0, -1);
the above statement gives me all elements .

how can I retrieve only  `beten` records using id= 222 ?

**Comment by neuecc** [comment]
You can't.
RedisList is same as `List<T>`, you can retrieve only index or range.
If you needs by id, use `RedisDictionary` or `RedisHash`, it is same as `Dictionary<TKey, TValue>`.

``` csharp
var server = new CloudStructures.RedisSettings("127.0.0.1:6379");
var list = new RedisDictionary<int, Customer>(server, "customer-key");
await list.Delete();
await list.Set(new[]
{
    new KeyValuePair<int, Customer> (111, new Customer { Id = 111, Name = "abcus" }),
    new KeyValuePair<int, Customer> (222, new Customer { Id = 222, Name = "beten" }),
    new KeyValuePair<int, Customer> (333, new Customer { Id = 333, Name = "censor" }),
    new KeyValuePair<int, Customer> (444, new Customer { Id = 444, Name = "dany" } )
});

var beten = (await list.Get(222)).GetValueOrDefault();

Console.WriteLine(beten.Name);
```

**Comment by ashuthinks** [comment]
Perfect thanks :)
