### ISSUE TITLE
base class' values are not saved in Redis Server.

### ISSUE THREAD

**Issue by firstboos** [neuecc/CloudStructures#5]
I write sample code using CloudStructures.Redis.
I stored values in the "Child" class inherits the "Person" class and run (Redis)Set().

``` c#
public class Person
{
        public string Name { get; set; }
        public int Age { get; set; }
}

public class Child : Person
{
        public int Sex { get; set; } 
        public string LastName { get; set; }
}
[TestMethod]
 public void TestMethod1()
 {
        var redisObj = new RedisString<Child>(redisSetting, "idid");
        Child child = new Child();
        child.Name = "Alice";
        child.Age = 18;
        child.Sex = 1;
        redisObj.Set(child);
}
```

But in Redis Server Saved values are "{sex:1, LastName:null}. What's wrong?? Why is not seen member variable "name", "age" ?. Of Course, I writed "Person" instance to save in Redis, It's no Problem.

``` c
127.0.0.1:6379> get idid
"\xef\xbb\xbf{\"Sex\":1,\"LastName\":null}"
```

Please help.

**Comment by phinett** [comment]
Keen to give this client a go, however showstopper right at the very beginning is this exact issue.

Is there a solution / workaround for this?
