### ISSUE TITLE
How to add collection and add key generically using dictionary? 

### ISSUE THREAD

**Issue by ashuthinks** [neuecc/CloudStructures#6]
I tried like following 

 var Settings = new RedisSettings("localhost");
 public async void SetData< T >(IEnumerable< T > collection, string Key)
        {
            RedisDictionary< object, T > mydictionary = new RedisDictionary< object, T >(Settings, typeof(T).Name);
//how to add collection data into `dictionary`
// i tried like following but failed 
  await mydictionary.Set(new[] { new KeyValuePair< object, IEnumerable< T > >(Key, collection) });

but it is not able to insert value into redis dictionary :(

**Comment by neuecc** [comment]
You can change the dictionary type.

``` csharp
var mydictionary = new RedisDictionary<object, IEnumerable<T>>(Settings, typeof(T).Name);

// more better
var mydictionary = new RedisDictionary<string, IEnumerable<T>>(Settings, typeof(T).Name);
```

**Comment by ashuthinks** [comment]
I tried the same code but it is uanble to add data into redis cache , why so?
because in Set I have to iterate through collection and want to add one by one values into KeyValuePair.
Can you help me ?
I tried like 
 // Add collection to dictionary;
            for (int i = 0; i < collection.Count(); i++)
            {
                await dictionary.Set(new[] { new KeyValuePair< object, IEnumerable < T > >(typeof(T).GetType().GetProperty(propertyName).GetValue(typeof(T),null), collection.ElementAt(i) });
            }
