### ISSUE TITLE
Multiple build errors in VS 2013/2015

### ISSUE THREAD

**Issue by jovball** [neuecc/CloudStructures#8]
I get a number of build errors from both Visual Studio 2013 and 2015. For example, VS 2013 doesn't like the $ prefix in SortedSetResult.cs on lines 22 and 41. RedisSubject.cs won't compile in VS 2015. 

Also, what's up with the mixture of BookSleeve and StackExchange.Redis? It appears that only part of this has been converted to StackExchange.Redis. I'm not sure what state this project is in.

**Comment by neuecc** [comment]
Solution File only supports on Visual Studio 2015.
`CloudStructures.Rx` (`RedisSubject`) is dropped development currently.
